version: "3.9"
services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/expenses
      - DATABASE_USERNAME=expenses
      - DATABASE_PASSWORD=expenses123
  database:
    image: postgres
    container_name: expenses_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: expenses123
      POSTGRES_USER: expenses
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
volumes:
  postgres_data: