version: "3.9"
services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: postgres
    container_name: expenses_database
    environment:
      POSTGRES_PASSWORD: expenses123
      POSTGRES_USER: expenses
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"